# Generated by Django 4.0.6 on 2022-07-25 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('newsportal', '0002_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(through='newsportal.Subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
